import AIFeatures from '@/components/HomePage/AIFeatures';
import Features from '@/components/HomePage/Features';
import ProductShowcase from '@/components/HomePage/ProductShowcase';
import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main id='main' className='home-refresh'>
        <header className='hero exhibition pine'>
          <div className='fv-container'>
            <div className='intro'>
              <div className='headlines'>
                <h1>
                  Your Complete Legal Tech Stack, <span className='highlight'>Supercharged</span> by AI
                </h1>
                <div className='cta'>
                  <a href='/demo-request/' id='home-cta-demo' className='btn btn-primary'>
                    Get a Demo
                  </a>
                  <a href='/pricing/' id='home-cta-pricing' className='btn btn-primary-outline'>
                    See Our Pricing
                  </a>
                </div>
              </div>
            </div>
            <div className='exhibition-media'>
              <div
                id='exhibition-carousel'
                className='carousel slide carousel-fade'
                data-ride='carousel'
                data-interval='3000'
              >
                <div className='carousel-inner'>
                  <div className='carousel-item'>
                    <picture>
                      <source
                        media='(max-width: 575px)'
                        srcSet='
                          https://filevine-marketing-production-media.s3.us-west-2.amazonaws.com/media/images/home/hero/exhibition/sm/exhibit-activity.webp
                        '
                      />
                      <source
                        media='(max-width: 768px)'
                        srcSet='
                          https://filevine-marketing-production-media.s3.us-west-2.amazonaws.com/media/images/home/hero/exhibition/md/exhibit-activity.webp
                        '
                      />
                      <source
                        srcSet='
                          https://filevine-marketing-production-media.s3.us-west-2.amazonaws.com/media/images/home/hero/exhibition/exhibit-activity.webp
                        '
                        type='image/webp'
                      />
                      <img
                        src='https://filevine-marketing-production-media.s3.us-west-2.amazonaws.com/media/images/home/hero/exhibition/exhibit-activity.png'
                        className='d-block w-100'
                        alt='App Screen: Activity Tab with project updates and vitals'
                      />
                    </picture>
                  </div>
                  <div className='carousel-item active'>
                    <picture>
                      <source
                        media='(max-width: 575px)'
                        srcSet='
                          https://filevine-marketing-production-media.s3.us-west-2.amazonaws.com/media/images/home/hero/exhibition/sm/exhibit-demands.webp
                        '
                      />
                      <source
                        media='(max-width: 768px)'
                        srcSet='
                          https://filevine-marketing-production-media.s3.us-west-2.amazonaws.com/media/images/home/hero/exhibition/md/exhibit-demands.webp
                        '
                      />
                      <source
                        srcSet='
                          https://filevine-marketing-production-media.s3.us-west-2.amazonaws.com/media/images/home/hero/exhibition/exhibit-demands.webp
                        '
                        type='image/webp'
                      />
                      <img
                        src='https://filevine-marketing-production-media.s3.us-west-2.amazonaws.com/media/images/home/hero/exhibition/exhibit-demands.png'
                        className='d-block w-100'
                        alt=''
                      />
                    </picture>
                  </div>
                  <div className='carousel-item'>
                    <picture>
                      <source
                        media='(max-width: 575px)'
                        srcSet='
                          https://filevine-marketing-production-media.s3.us-west-2.amazonaws.com/media/images/home/hero/exhibition/sm/exhibit-documents.webp
                        '
                      />
                      <source
                        media='(max-width: 768px)'
                        srcSet='
                          https://filevine-marketing-production-media.s3.us-west-2.amazonaws.com/media/images/home/hero/exhibition/md/exhibit-documents.webp
                        '
                      />
                      <source
                        srcSet='
                          https://filevine-marketing-production-media.s3.us-west-2.amazonaws.com/media/images/home/hero/exhibition/exhibit-documents.webp
                        '
                        type='image/webp'
                      />
                      <img
                        src='https://filevine-marketing-production-media.s3.us-west-2.amazonaws.com/media/images/home/hero/exhibition/exhibit-documents.png'
                        className='d-block w-100'
                        alt=''
                      />
                    </picture>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </header>
        <div id='top-section' className='light file-separator'>
          <section id='section-1' className='accordion-side-by-side pt-0 null'>
            <div className='fv-container'>
              <div className='action-header'>
                <div className='headline'>
                  <div className='kicker mb-4'>How it works</div>
                  <h2>
                    AI powered legal technology that <span className='highlight'>accelerates your entire firm</span>
                  </h2>
                </div>
                <div className='headline-cta'>
                  <a href='/demo-request/' className='btn btn-primary'>
                    Schedule a Free Demo
                  </a>
                </div>
              </div>
              <Features />
            </div>
          </section>
          <ProductShowcase />
        </div>
        <AIFeatures />
        <section id='brag-tab-' className='brag-tabs file-separator light'>
          <div className='fv-container'>
            <div className='fv-row'>
              <div className='headline'>
                <h2></h2>
              </div>
            </div>
            <div className='fv-row'>
              <div id='brag-accordion' className='sbs-layout'>
                <div id='card-1' className='card accordion-card'>
                  <div className='card-header' id='heading-1'>
                    <button
                      className='btn btn-link'
                      data-toggle='collapse'
                      data-target='#brag-1'
                      aria-expanded='true'
                      aria-controls='#brag-1'
                    >
                      <div className='btn-headline'>Integrations</div>
                      <div className='accordion-arrow'>
                        <svg xmlns='http://www.w3.org/2000/svg' width='14' height='9' viewBox='0 0 14 9' fill='none'>
                          <path
                            fillRule='evenodd'
                            clipRule='evenodd'
                            d='M13.7071 8.20711C13.3166 8.59763 12.6834 8.59763 12.2929 8.20711L7 2.91421L1.70711 8.20711C1.31658 8.59763 0.683417 8.59763 0.292894 8.20711C-0.0976314 7.81658 -0.0976314 7.18342 0.292893 6.79289L6.29289 0.792893C6.68342 0.402369 7.31658 0.402369 7.70711 0.792893L13.7071 6.79289C14.0976 7.18342 14.0976 7.81658 13.7071 8.20711Z'
                            fill='currentColor'
                          ></path>
                        </svg>
                      </div>
                    </button>
                  </div>
                  <div
                    id='brag-1'
                    className='accordion-content collapse show'
                    aria-labelledby='heading-1'
                    data-parent='#brag-accordion'
                  >
                    <div className='card-body brag'>
                      <div className='body-content'>
                        Filevine integrates with all of your favorite apps and existing technology.
                      </div>
                      <a href='/integrations/' className='link-arrow'>
                        Learn more about Integrations&nbsp;<span>›</span>
                      </a>
                    </div>
                  </div>
                </div>
                <div id='media-body-1' className='accordion-media show collapse' data-parent='#card-3'>
                  <figure>
                    <picture>
                      <source
                        srcSet='
                          https://filevine-marketing-production-media.s3.amazonaws.com/media/images/flex/section/2023/09/brag-integrations.webp
                        '
                        type='image/webp'
                      />
                      <img
                        src='https://filevine-marketing-production-media.s3.amazonaws.com/media/images/flex/section/2023/08/brag-integrations.png'
                        alt=''
                        className='img-fluid'
                      />
                    </picture>
                  </figure>
                </div>
                <div id='card-2' className='card accordion-card'>
                  <div className='card-header' id='heading-2'>
                    <button
                      className='btn btn-link collapsed'
                      data-toggle='collapse'
                      data-target='#brag-2'
                      aria-expanded='false'
                      aria-controls='#brag-2'
                    >
                      <div className='btn-headline'>Security</div>
                      <div className='accordion-arrow'>
                        <svg xmlns='http://www.w3.org/2000/svg' width='14' height='9' viewBox='0 0 14 9' fill='none'>
                          <path
                            fillRule='evenodd'
                            clipRule='evenodd'
                            d='M13.7071 8.20711C13.3166 8.59763 12.6834 8.59763 12.2929 8.20711L7 2.91421L1.70711 8.20711C1.31658 8.59763 0.683417 8.59763 0.292894 8.20711C-0.0976314 7.81658 -0.0976314 7.18342 0.292893 6.79289L6.29289 0.792893C6.68342 0.402369 7.31658 0.402369 7.70711 0.792893L13.7071 6.79289C14.0976 7.18342 14.0976 7.81658 13.7071 8.20711Z'
                            fill='currentColor'
                          ></path>
                        </svg>
                      </div>
                    </button>
                  </div>
                  <div
                    id='brag-2'
                    className='accordion-content collapse'
                    aria-labelledby='heading-2'
                    data-parent='#brag-accordion'
                  >
                    <div className='card-body brag'>
                      <div className='body-content'>
                        We use best-in-class information security tools to safeguard your data.
                      </div>
                      <a href='/security/' className='link-arrow'>
                        Learn more about Security&nbsp;<span>›</span>
                      </a>
                    </div>
                  </div>
                </div>
                <div id='media-body-2' className='accordion-media collapse' data-parent='#card-3'>
                  <figure>
                    <picture>
                      <source
                        srcSet='
                          https://filevine-marketing-production-media.s3.amazonaws.com/media/images/flex/section/2023/09/brag-security.webp
                        '
                        type='image/webp'
                      />
                      <img
                        src='https://filevine-marketing-production-media.s3.amazonaws.com/media/images/flex/section/2023/08/brag-security.png'
                        alt=''
                        className='img-fluid'
                      />
                    </picture>
                  </figure>
                </div>
                <div id='card-3' className='card accordion-card'>
                  <div className='card-header' id='heading-3'>
                    <button
                      className='btn btn-link collapsed'
                      data-toggle='collapse'
                      data-target='#brag-3'
                      aria-expanded='false'
                      aria-controls='#brag-3'
                    >
                      <div className='btn-headline'>Awards and Reviews</div>
                      <div className='accordion-arrow'>
                        <svg xmlns='http://www.w3.org/2000/svg' width='14' height='9' viewBox='0 0 14 9' fill='none'>
                          <path
                            fillRule='evenodd'
                            clipRule='evenodd'
                            d='M13.7071 8.20711C13.3166 8.59763 12.6834 8.59763 12.2929 8.20711L7 2.91421L1.70711 8.20711C1.31658 8.59763 0.683417 8.59763 0.292894 8.20711C-0.0976314 7.81658 -0.0976314 7.18342 0.292893 6.79289L6.29289 0.792893C6.68342 0.402369 7.31658 0.402369 7.70711 0.792893L13.7071 6.79289C14.0976 7.18342 14.0976 7.81658 13.7071 8.20711Z'
                            fill='currentColor'
                          ></path>
                        </svg>
                      </div>
                    </button>
                  </div>
                  <div
                    id='brag-3'
                    className='accordion-content collapse'
                    aria-labelledby='heading-3'
                    data-parent='#brag-accordion'
                  >
                    <div className='card-body brag'>
                      <div className='body-content'>
                        Thousands of attorneys, administrators, and paralegals trust Filevine to manage their legal work
                        from start to finish.
                      </div>
                    </div>
                  </div>
                </div>
                <div id='media-body-3' className='accordion-media collapse' data-parent='#card-3'>
                  <figure>
                    <picture>
                      <source
                        srcSet='
                          https://filevine-marketing-production-media.s3.amazonaws.com/media/images/flex/section/2023/09/brag-best-in-class.webp
                        '
                        type='image/webp'
                      />
                      <img
                        src='https://filevine-marketing-production-media.s3.amazonaws.com/media/images/flex/section/2023/08/brag-best-in-class.png'
                        alt=''
                        className='img-fluid'
                      />
                    </picture>
                  </figure>
                </div>
                <div id='card-4' className='card accordion-card'>
                  <div className='card-header' id='heading-4'>
                    <button
                      className='btn btn-link collapsed'
                      data-toggle='collapse'
                      data-target='#brag-4'
                      aria-expanded='false'
                      aria-controls='#brag-4'
                    >
                      <div className='btn-headline'>Partners</div>
                      <div className='accordion-arrow'>
                        <svg xmlns='http://www.w3.org/2000/svg' width='14' height='9' viewBox='0 0 14 9' fill='none'>
                          <path
                            fillRule='evenodd'
                            clipRule='evenodd'
                            d='M13.7071 8.20711C13.3166 8.59763 12.6834 8.59763 12.2929 8.20711L7 2.91421L1.70711 8.20711C1.31658 8.59763 0.683417 8.59763 0.292894 8.20711C-0.0976314 7.81658 -0.0976314 7.18342 0.292893 6.79289L6.29289 0.792893C6.68342 0.402369 7.31658 0.402369 7.70711 0.792893L13.7071 6.79289C14.0976 7.18342 14.0976 7.81658 13.7071 8.20711Z'
                            fill='currentColor'
                          ></path>
                        </svg>
                      </div>
                    </button>
                  </div>
                  <div
                    id='brag-4'
                    className='accordion-content collapse'
                    aria-labelledby='heading-4'
                    data-parent='#brag-accordion'
                  >
                    <div className='card-body brag'>
                      <div className='body-content'>
                        Our robust partner network can enable your team to make the most out of your legal technology.
                      </div>
                      <a href='/partners/' className='link-arrow'>
                        Learn more about partners&nbsp;<span>›</span>
                      </a>
                    </div>
                  </div>
                </div>
                <div id='media-body-4' className='accordion-media collapse' data-parent='#card-3'>
                  <figure>
                    <picture>
                      <source
                        srcSet='
                          https://filevine-marketing-production-media.s3.amazonaws.com/media/images/flex/section/2023/09/brag-partners.webp
                        '
                        type='image/webp'
                      />
                      <img
                        src='https://filevine-marketing-production-media.s3.amazonaws.com/media/images/flex/section/2023/09/brag-partners.png'
                        alt=''
                        className='img-fluid'
                      />
                    </picture>
                  </figure>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section id='helpful-resources' className='  '>
          <div className='fv-container'>
            <div className='fv-row intro d-flex justify-content-center'>
              <div className='col-md-8'>
                <div className='kicker text-center'>Resources</div>
                <h2 className='text-center mb-5'>Check out what’s been going on</h2>
              </div>
            </div>
            <div className='fv-cards justify-content-center row-cols-1 row-cols-md-2 row-cols-lg-3'>
              <a href='/blog/will-legal-ai-make-you-irrelevant-or-unstoppable/'>
                <div className='fv-card resource-card'>
                  <div className='card-header'>
                    <img
                      src='https://filevine-marketing-production-media.s3.amazonaws.com/media/images/blogs/2023/06/artificial-intelligence-irrelevant-or-unstoppable.jpg'
                      className='img-fluid'
                      loading='lazy'
                      alt=''
                    />
                  </div>
                  <div className='card-body'>
                    <div className='chip chip-black chip-tag'>
                      <div className='chip-title'>BLOG POST</div>
                    </div>
                    <h3 className='h4'>Will Legal AI Make You Irrelevant — or Unstoppable?</h3>
                  </div>
                  <div className='card-footer'>
                    <button href='/blog/will-legal-ai-make-you-irrelevant-or-unstoppable/' className='btn text-link'>
                      Read Post&nbsp;<span className='link-arrow'>›</span>
                    </button>
                  </div>
                </div>
              </a>
              <a href='/blog/secure-and-reliable-the-future-of-legal-payment-processing/'>
                <div className='fv-card resource-card'>
                  <div className='card-header'>
                    <img
                      src='https://filevine-marketing-production-media.s3.amazonaws.com/media/images/blogs/2023/08/10_cover.png'
                      className='img-fluid'
                      loading='lazy'
                      alt=''
                    />
                  </div>
                  <div className='card-body'>
                    <div className='chip chip-black chip-tag'>
                      <div className='chip-title'>BLOG POST</div>
                    </div>
                    <h3 className='h4'>Secure and Reliable: The Future of Legal Payment Processing</h3>
                  </div>
                  <div className='card-footer'>
                    <button
                      href='/blog/secure-and-reliable-the-future-of-legal-payment-processing/'
                      className='btn text-link'
                    >
                      Read Post&nbsp;<span className='link-arrow'>›</span>
                    </button>
                  </div>
                </div>
              </a>
              <a href='/customers/case-studies/hacking-immigration-law-legalfile-growth/'>
                <div className='fv-card resource-card'>
                  <div className='card-header'>
                    <img
                      src='https://filevine-marketing-production-media.s3.amazonaws.com/media/images/social/case-studies/2022/12/hacking-immigration-law-case-study.png'
                      className='img-fluid'
                      loading='lazy'
                      alt=''
                    />
                  </div>
                  <div className='card-body'>
                    <div className='chip chip-black chip-tag'>
                      <div className='chip-title'>CASE STUDY</div>
                    </div>
                    <h3 className='h4'>Hacking Immigration Law + Filevine = Growth</h3>
                  </div>
                  <div className='card-footer'>
                    <button
                      href='/customers/case-studies/hacking-immigration-law-legalfile-growth/'
                      className='btn text-link'
                    >
                      Read the Case Study&nbsp;<span className='link-arrow'>›</span>
                    </button>
                  </div>
                </div>
              </a>
            </div>
          </div>
        </section>
        <section id='final-cta' className='cta plain'>
          <div className='container'>
            <div className='row justify-content-center'>
              <div className='col-md-8 text-center'>
                <div className='headline'>
                  <h2 className='mb-5'>See all that Filevine can do with a customized demonstration from our team</h2>
                </div>
                <a href='/demo-request/' className='btn btn-primary'>
                  Schedule a Demo
                </a>
              </div>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
